version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sambha-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sambha123
      MONGO_INITDB_DATABASE: sambha
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - sambha-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: sambha-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sambha-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: development
    container_name: sambha-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:sambha123@mongodb:27017/sambha?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key
      CORS_ORIGIN: http://localhost:3000,http://localhost:3002
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/backend/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - sambha-network
    command: pnpm dev

  # Web Application
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    container_name: sambha-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_STARKNET_NETWORK: goerli
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    networks:
      - sambha-network
    command: pnpm dev

  # Landing Page
  landing:
    build:
      context: .
      dockerfile: apps/landing/Dockerfile
      target: development
    container_name: sambha-landing
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - ./apps/landing:/app/apps/landing
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/landing/node_modules
      - /app/apps/landing/.next
    networks:
      - sambha-network
    command: pnpm dev

  # StarkNet Node (for local development)
  starknet-devnet:
    image: shardlabs/starknet-devnet-rs:latest
    container_name: sambha-starknet-devnet
    restart: unless-stopped
    ports:
      - "5050:5050"
    command:
      [
        "--host",
        "0.0.0.0",
        "--port",
        "5050",
        "--seed",
        "0",
        "--accounts",
        "10",
        "--initial-balance",
        "1000000000000000000000",
      ]
    networks:
      - sambha-network

volumes:
  mongodb_data:
  redis_data:

networks:
  sambha-network:
    driver: bridge
